In [1]:
from pandas import read_html
import pandas as pd
from pandas import Series, DataFrame
import seaborn as sns
import matplotlib as plt
import sklearn

/usr/local/lib/python2.7/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py:800: MatplotlibDeprecationWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  mplDeprecation)

In [ ]:
url = 'https://www.basketball-reference.com/leagues/NBA_1986_ratings.html'
dframe_list = pd.io.html.read_html(url)
dframe = dframe_list[0]
dframe['Year'] = Series ([1986 for i in range(len(dframe.index))])
dframe.head()

In [ ]:
for x in range(1987,2016):
    url = 'https://www.basketball-reference.com/leagues/NBA_%d_ratings.html' %x
    dframe_list = pd.io.html.read_html(url)
    dframe1 = dframe_list[0]
    dframe1['Year'] = Series ([x for i in range(len(dframe.index))])
    dframe = dframe.append(dframe1)

In [ ]:
dframe.columns = dframe.columns.droplevel()

In [ ]:
dframe = dframe.rename({"Rk":"Rank"},axis='columns')
dframe.rename(columns = {"": "Year"},inplace=True)
regular_season_dframe = dframe
regular_season_dframe.to_csv("Regular_Season.csv",index=False)

In [ ]:
regular_season_dframe.head()

In [2]:
from bs4 import BeautifulSoup
import urllib

In [3]:
Champions_df = DataFrame(columns = ['Year','Team'])
Champions_df

Empty DataFrame
Columns: [Year, Team]
Index: []

In [4]:
def Champion (element,year):
    index = str(element).find(".html\">")
    index = index + 7
    Team = str(element)[index:str(element).find("</a><")]
    series = Series (data = [year,Team],index = ['Year','Team'])
    return series

In [5]:
for x in range (1986,2018):
    html = 'https://www.basketball-reference.com/playoffs/NBA_%d.html' %x
    r = urllib.urlopen(html).read()
    soup = BeautifulSoup(r,'lxml')
    list1=[]
    for text in soup.find_all('p'):
        list1.append(text)
    element = list1[2]
    Champions_df = Champions_df.append(Champion(element,x),ignore_index=True)
#Champions_df = Champions_df[0:33]

In [112]:
Champions_df.head()

   Year                Team
0  1986      Boston Celtics
1  1987  Los Angeles Lakers
2  1988  Los Angeles Lakers
3  1989     Detroit Pistons
4  1990     Detroit Pistons

In [84]:
url1 = 'https://www.basketball-reference.com/playoffs/NBA_2017.html'
dframe_list1 = pd.io.html.read_html(url1)
dframe2 = dframe_list1[16]
b = dframe2['Team'][2:16]
c = dframe2['Team'][0:2]
c
#dframe2.head()

0      Cleveland Cavaliers
1    Golden State Warriors
Name: Team, dtype: object

In [32]:
a  = dframe2.loc[dframe2['Team']== "Golden State Warriors",'Team':'G'].drop(columns = 'G')

In [33]:
positions = Series([1,2,3,3,4,4,4,4,5,5,5,5,5,5,5,5])

In [114]:
df = DataFrame()
df['Position'] = positions

teams = dframe2.loc[dframe2['Team']== "Golden State Warriors",'Team'].index[0]
team = dframe2.iloc[0]['Team']
index = dframe.loc[Champions_df['Year']== 2016,'Team']
#teams = teams.reset_index()
#teams.drop(columns = 'index',inplace=True)
c = c.loc[c != team]
team
#teams = teams.append(c)
#teams = teams.append(b)
#Champions_df['Team'][Champions_df['Year'] == 2016]
#df['Teams'] = teams
#df['Year'] = Series(2016,teams.index)
#df.head()
#newseries =
#s = Series([newseries],index=[0])
#c = b.tolist()
#c = Series(c)
#s.append(c)
#df['Team'] = b

u'Cleveland Cavaliers'

In [138]:
playoff_teams = DataFrame()
for x in range (1986,2018):
    url1 = 'https://www.basketball-reference.com/playoffs/NBA_%d.html' %x
    dframe_list = pd.io.html.read_html(url1)
    raw_dframe = dframe_list[16]
    teams_not_in_finals = dframe['Team'][2:16]
    finalists = dframe['Team'][0:2]
    df = DataFrame()
    positions = Series([0,1,2,3,3,4,4,4,4,5,5,5,5,5,5,5,5])
    df['Position'] = positions
    championsindex = int(x-1986)
    championteam = Champions_df.iloc[championsindex]['Team']
    teams = Champions_df.iloc[championsindex]
    finalists = finalists.loc[finalists != championteam]
    teams = teams.append(finalists,ignore_index=True)
    teams = teams.append(teams_not_in_finals,ignore_index=True)
    teams = teams.drop(index = [0])
    df['Teams'] = teams
    df['Year'] = Series(x,teams.index)
    df = df.drop(index= [0])
    playoff_teams = playoff_teams.append(df,ignore_index=True)

In [139]:
playoff_teams

     Position                   Teams    Year
0           1          Boston Celtics  1986.0
1           2   Golden State Warriors  1986.0
2           3     Cleveland Cavaliers  1986.0
3           3   Oklahoma City Thunder  1986.0
4           4         Toronto Raptors  1986.0
5           4              Miami Heat  1986.0
6           4  Portland Trail Blazers  1986.0
7           4       San Antonio Spurs  1986.0
8           5           Atlanta Hawks  1986.0
9           5          Indiana Pacers  1986.0
10          5       Charlotte Hornets  1986.0
11          5    Los Angeles Clippers  1986.0
12          5          Boston Celtics  1986.0
13          5        Dallas Mavericks  1986.0
14          5         Houston Rockets  1986.0
15          5         Detroit Pistons  1986.0
16          1      Los Angeles Lakers  1987.0
17          2   Golden State Warriors  1987.0
18          3     Cleveland Cavaliers  1987.0
19          3   Oklahoma City Thunder  1987.0
20          4         Toronto Raptors  1987.0
21          4              Miami Heat  1987.0
22          4  Portland Trail Blazers  1987.0
23          4       San Antonio Spurs  1987.0
24          5           Atlanta Hawks  1987.0
25          5          Indiana Pacers  1987.0
26          5       Charlotte Hornets  1987.0
27          5    Los Angeles Clippers  1987.0
28          5          Boston Celtics  1987.0
29          5        Dallas Mavericks  1987.0
..        ...                     ...     ...
482         3   Oklahoma City Thunder  2016.0
483         3         Toronto Raptors  2016.0
484         4              Miami Heat  2016.0
485         4  Portland Trail Blazers  2016.0
486         4       San Antonio Spurs  2016.0
487         4           Atlanta Hawks  2016.0
488         5          Indiana Pacers  2016.0
489         5       Charlotte Hornets  2016.0
490         5    Los Angeles Clippers  2016.0
491         5          Boston Celtics  2016.0
492         5        Dallas Mavericks  2016.0
493         5         Houston Rockets  2016.0
494         5         Detroit Pistons  2016.0
495         5       Memphis Grizzlies  2016.0
496         1   Golden State Warriors  2017.0
497         2     Cleveland Cavaliers  2017.0
498         3   Oklahoma City Thunder  2017.0
499         3         Toronto Raptors  2017.0
500         4              Miami Heat  2017.0
501         4  Portland Trail Blazers  2017.0
502         4       San Antonio Spurs  2017.0
503         4           Atlanta Hawks  2017.0
504         5          Indiana Pacers  2017.0
505         5       Charlotte Hornets  2017.0
506         5    Los Angeles Clippers  2017.0
507         5          Boston Celtics  2017.0
508         5        Dallas Mavericks  2017.0
509         5         Houston Rockets  2017.0
510         5         Detroit Pistons  2017.0
511         5       Memphis Grizzlies  2017.0

[512 rows x 3 columns]